class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start3'
        self.MirrorCommand = 'mirror3'
        self.UnzipMirrorCommand = 'unzipmirror3'
        self.TarMirrorCommand = 'tarmirror3'
        self.CancelMirror = 'cancel3'
        self.CancelAllCommand = 'cancelall3'
        self.ListCommand = 'search3'
        self.StatusCommand = 'status3'
        self.AuthorizeCommand = 'auth3'
        self.UnAuthorizeCommand = 'unauth3'
        self.AuthListCommand = 'users3'
        self.PingCommand = 'ping3'
        self.RestartCommand = 'restart3'
        self.StatsCommand = 'stats3'
        self.HelpCommand = 'help3'
        self.LogCommand = 'log3'
        self.SpeedCommand = 'speedtest3'
        self.CloneCommand = 'clone3'
        self.WatchCommand = 'watch3'
        self.TarWatchCommand = 'tarwatch3'
        self.DeleteCommand = 'delete3'
        self.UsageCommand = 'usage3'
        self.RepoCommand = 'repo3'

BotCommands = _BotCommands()
