class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start1'
        self.MirrorCommand = 'mirror1'
        self.UnzipMirrorCommand = 'unzipmirror1'
        self.TarMirrorCommand = 'tarmirror1'
        self.CancelMirror = 'cancel1'
        self.CancelAllCommand = 'cancelall1'
        self.ListCommand = 'search1'
        self.StatusCommand = 'status1'
        self.AuthorizeCommand = 'auth1'
        self.UnAuthorizeCommand = 'unauth1'
        self.AuthListCommand = 'users1'
        self.PingCommand = 'ping1'
        self.RestartCommand = 'restart1'
        self.StatsCommand = 'stats1'
        self.HelpCommand = 'help1'
        self.LogCommand = 'log1'
        self.SpeedCommand = 'speedtest1'
        self.CloneCommand = 'clone1'
        self.WatchCommand = 'watch1'
        self.TarWatchCommand = 'tarwatch1'
        self.DeleteCommand = 'delete1'
        self.UsageCommand = 'usage1'
        self.RepoCommand = 'repo1'

BotCommands = _BotCommands()
