class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start2'
        self.MirrorCommand = 'mirror2'
        self.UnzipMirrorCommand = 'unzipmirror2'
        self.TarMirrorCommand = 'tarmirror2'
        self.CancelMirror = 'cancel2'
        self.CancelAllCommand = 'cancelall2'
        self.ListCommand = 'search2'
        self.StatusCommand = 'status2'
        self.AuthorizeCommand = 'auth2'
        self.UnAuthorizeCommand = 'unauth2'
        self.AuthListCommand = 'users2'
        self.PingCommand = 'ping2'
        self.RestartCommand = 'restart2'
        self.StatsCommand = 'stats2'
        self.HelpCommand = 'help2'
        self.LogCommand = 'log2'
        self.SpeedCommand = 'speedtest2'
        self.CloneCommand = 'clone2'
        self.WatchCommand = 'watch2'
        self.TarWatchCommand = 'tarwatch2'
        self.DeleteCommand = 'delete2'
        self.UsageCommand = 'usage2'
        self.RepoCommand = 'repo2'

BotCommands = _BotCommands()
